### ISSUE TITLE
Python requirements

### ISSUE THREAD

**Issue by nadykl** [mgbckr/corals-lib-python#2]
Hello,
Could you please consider updating the setup requires to include support for Python 3.11?
I've done this manually and it worked fine for me (numba 0.57).
Thanks a lot for your package. It is very useful.

**Comment by mgbckr** [comment]
Thanks for the hint! Done and published as [Release 0.1.6](https://pypi.org/project/corals/0.1.6/).

**Comment by mgbckr** [comment]
Thanks for the hint! Done and published as [Release 0.1.6](https://pypi.org/project/corals/0.1.6/).
