### ISSUE TITLE
Error getting the topk cor for Pearson

### ISSUE THREAD

**Issue by SantosRAC** [mgbckr/corals-lib-python#3]
Dear @mgbckr , I hope you are doing well.

Thanks for this nice tool! I am glad to find one that can handle large-scale computation of correlations very fast!

I am getting some errors when I try to use the cor_topk for the Pearson correlation (which is also allowed to be selected in this method and which I initially planned to use in my analysis):

```bash
from corals.correlation.topk.default import cor_topk
cor_topk_values_pearson, cor_topk_coo_pearson = cor_topk(concatenated_transposed, correlation_type="pearson", k=0.001, n_jobs=8)
```

You can find the errors attached:

 * [error_corals_04152024.txt](https://github.com/mgbckr/corals-lib-python/files/14982565/error_corals_04152024.txt)

I also would like to mention that I had to change the imported module (from base to default; base did not work).

I am sharing the header (first 5 lines) of my pandas dataframe (which works with the full correlation and cor_topk method using Spearman). Columns are features (~19k) and lines are samples (~450):

![image](https://github.com/mgbckr/corals-lib-python/assets/7959954/845621fe-10b3-423d-aa31-c776c8bd6238)

Thank you very much once again.

**Comment by mgbckr** [comment]
Hi @SantosRAC 

the last bump to version `0.1.7` via #5 also fixed this issue :)
